server:
  port: 8040

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: api_order_route
          uri: lb://api-order
          predicates:
            - Path=/api/order/**
        - id: api_third_route
          uri: lb://api-third-party
          predicates:
            - Path=/api/third/**
        - id: api_backend_route
          uri: lb://api-backend
          predicates:
            - Path=/api/**


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: huangapi-rpc-nacos
  #  scan:
  #    base-packages: com.anyan.apigateway.provider
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false